# netlify.toml

[build]
  # Comando para construir tu Next.js
  command   = "npm run build"
  # Directorio donde Netlify recogerá tus funciones (las genera el plugin)
  functions = "netlify/functions"

[[plugins]]
  # Plugin oficial de Next.js
  package = "@netlify/plugin-nextjs"
